# Generated by Django 5.1.1 on 2024-10-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='document',
        ),
    ]
