# Generated by Django 5.1.1 on 2024-10-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_remove_contract_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
