# Generated by Django 5.1.1 on 2024-09-17 05:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=500)),
                ('code', models.PositiveSmallIntegerField(editable=False, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Physical'), (2, 'Legal'), (3, 'Others')], default=2)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('inn', models.CharField(blank=True, max_length=9, null=True)),
                ('register_date', models.DateField(blank=True, null=True)),
                ('register_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['-created_at'],
            },
        ),
    ]
