# Generated by Django 5.1.1 on 2024-09-17 05:25

import django.db.models.deletion
import inventory.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('contract', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=500)),
                ('code', models.PositiveSmallIntegerField(editable=False)),
                ('amount', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('qqs', models.BooleanField()),
                ('date', models.DateField()),
                ('terminate_date', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='contract.contract')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='common.inventorygroup', validators=[inventory.models.validate_group])),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='common.measureunit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='organization.organization')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='common.inventorytype')),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
