# Generated by Django 5.1.1 on 2024-10-20 16:35

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='qr_file',
            field=models.FileField(blank=True, null=True, upload_to=inventory.models.qr_file_upload_to),
        ),
    ]
