# Generated by Django 5.1.1 on 2024-09-17 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktaking',
            fields=[
                ('number', models.PositiveBigIntegerField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('terminate_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktakings', to='employee.employee')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktakings', to='inventory.inventory')),
            ],
            options={
                'db_table': 'stocktaking',
                'ordering': ['-created_at'],
            },
        ),
    ]
