# Generated by Django 5.1.1 on 2024-10-21 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktaking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stocktaking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='stocktaking.stocktaking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspection',
                'ordering': ['-created_at'],
                'unique_together': {('stocktaking', 'created_at')},
            },
        ),
    ]
